force-app/main/default/objects/SC_Gemini_Email_Response__c/SC_Gemini_Email_Response__c.object-meta.xml
<CustomObject>
    <label>Gemini Email Response</label>
    <nameField>
        <label>Gemini Email Response Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Gemini Email Responses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SC_Gemini_Email_Response__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Gemini Email Responses</relationshipLabel>
    <relationshipName>Gemini_Email_Responses</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SC_Gemini_Email_Response__c/fields/Gemini_Response__c.field-meta.xml
<CustomField>
    <fullName>Gemini_Response__c</fullName>
    <label>Gemini Response</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/SC_Gemini_Email_Response__c/fields/Gemini_Score__c.field-meta.xml
<CustomField>
    <fullName>Gemini_Score__c</fullName>
    <label>Gemini Score</label>
    <precision>18</precision>
    <scale>12</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/SC_Gemini_Email_Response__c/fields/Gemini_Score_Text__c.field-meta.xml
<CustomField>
    <fullName>Gemini_Score_Text__c</fullName>
    <label>Gemini Score Text</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SC_Gemini_Email_Response__c/fields/Gemini_Sync_Status__c.field-meta.xml
<CustomField>
    <fullName>Gemini_Sync_Status__c</fullName>
    <label>Gemini Sync Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Exported</fullName>
            </value>
            <value>
                <fullName>Error</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SC_Gemini_Email_Response__c/fields/Prompt__c.field-meta.xml
<CustomField>
    <fullName>Prompt__c</fullName>
    <label>Prompt</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/SC_Gemini_Email_Response__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
            </value>
            <value>
                <fullName>Email Sent</fullName>
            </value>
            <value>
                <fullName>Case Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SC_Gemini_Email_Response__c/fields/User_Hint__c.field-meta.xml
<CustomField>
    <fullName>User_Hint__c</fullName>
    <label>User Hint</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/SC_Gemini_Settings__c/SC_Gemini_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>SC Gemini Settings</label>
</CustomObject>

force-app/main/default/objects/SC_Gemini_Settings__c/fields/Email_Template_Body_Parameter__c.field-meta.xml
<CustomField>
    <fullName>Email_Template_Body_Parameter__c</fullName>
    <label>Email Template Body Parameter</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SC_Gemini_Settings__c/fields/Gemini_Email_Template_Developer_Name__c.field-meta.xml
<CustomField>
    <fullName>Gemini_Email_Template_Developer_Name__c</fullName>
    <label>Gemini Email Template Developer Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/SC_GeminiEmailResponseInvocable.cls
public with sharing class SC_GeminiEmailResponseInvocable {
    private static final String NEW_STATUS = 'New';
    private static final String DRAFT_STATUS = 'Draft';
    private static final String SUCCESS_STATUS = 'success';

    @InvocableMethod
    public static List<FlowInput> createGeminiEmailResponse(List<FlowOutput> flowParameters) {
        List<FlowInput> flowInputs = new List<FlowInput>();

        for (FlowOutput p : flowParameters) {
            Case c = [SELECT Id, OwnerId, Description, SuppliedEmail, Account.Name, Subject FROM Case WHERE Id = :p.caseId];
            EmailMessage e = createEmailMessageDraft(c, p.emailAddress, p.geminiResponse);

            createGeminiResponse(c, e, p);

            flowInputs.add(new FlowInput(SUCCESS_STATUS));
        }

        return flowInputs;
    }

    private static EmailMessage createEmailMessageDraft(Case c, String emailAddress, String geminiCaseResponse) {
        SC_Gemini_Settings__c geminiSettings = SC_Gemini_Settings__c.getOrgDefaults();
        String responseHtml;
        EmailMessage m = new EmailMessage();
        String formattedResponse = geminiCaseResponse.replace(' ', '&nbsp;').replace('\n', '<br/>');
        if (String.isNotBlank(geminiSettings.Gemini_Email_Template_Developer_Name__c)) {
            EmailTemplate et = [SELECT Id, HtmlValue FROM EmailTemplate WHERE DeveloperName = :geminiSettings.Gemini_Email_Template_Developer_Name__c];        
            responseHtml = et.HtmlValue.replace(geminiSettings.Email_Template_Body_Parameter__c, formattedResponse);
            responseHtml = responseHtml.replace('<html style="overflow-y: hidden;">','<html>');
        } else {
            responseHtml = formattedResponse;
            responseHtml = responseHtml.replace('<html style="overflow-y: hidden;">','<html>');
        }

        m.IsPrivateDraft = true;
        //m.Subject = 'RE: ' + c.Subject;
        m.Subject = 'Les magasins U vous répondent';
        m.RelatedToId = c.Id;
        m.Status = '5';
        m.FromAddress = emailAddress;
        m.ToAddress = c.SuppliedEmail;
        m.HtmlBody = responseHtml;

        insert m;

        return m;
    }

    private static void createGeminiResponse(Case c, EmailMessage e, FlowOutput p) {
        SC_Gemini_Email_Response__c r = new SC_Gemini_Email_Response__c();

        r.Email_Message_Id__c = e.Id;
        r.Gemini_Response__c = p.geminiResponse;
        r.Gemini_Sync_Status__c = NEW_STATUS;
        r.Gemini_Score__c = p.geminiScore;
        r.User_Hint__c = p.userHint;
        r.Gemini_Score_Text__c = p.geminiScoreText;
        r.Prompt__c = p.prompt;
        r.Status__c = DRAFT_STATUS;
        r.Case__c = c.Id;

        insert r;
    }

    public class FlowOutput {
        @InvocableVariable
        public String caseId;
        @InvocableVariable
        public String emailAddress;
        @InvocableVariable
        public String prompt;
        @InvocableVariable
        public String userHint;
        @InvocableVariable
        public String geminiResponse;
        @InvocableVariable
        public Decimal geminiScore;
        @InvocableVariable
        public String geminiScoreText;
    }

    public class FlowInput {
        @InvocableVariable
        public String status;

        public FlowInput(String status) {
            this.status = status;
        }
    }
}