force-app/main/default/objects/Account/fields/CommercialSignLabel__c.field-meta.xml
<CustomField>
    <fullName>CommercialSignLabel__c</fullName>
    <label>Enseigne Commerciale</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/StoreEmail__c.field-meta.xml
<CustomField>
    <fullName>StoreEmail__c</fullName>
    <label>Email du magasin</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Account/fields/StoreId__c.field-meta.xml
<CustomField>
    <fullName>StoreId__c</fullName>
    <externalId>true</externalId>
    <label>Code Magasin</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/User/fields/StoreId__c.field-meta.xml
<CustomField>
    <fullName>StoreId__c</fullName>
    <description>To store the store id of the user</description>
    <externalId>true</externalId>
    <label>StoreId</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/accountheaderCtrl.cls
/**
* @author : 
* @date : 23/04/2020
* @description : class to handle the account header
* @last modified date/comments :
*/
public without sharing class accountheaderCtrl {
    //without sharing due to usage as guest user (better than open sharing)

    @AuraEnabled(Cacheable = true)
    public static Account getAccount(String storeId) {
        System.debug(LoggingLevel.DEBUG,'storeId: ' + storeId);
        if(String.isNotBlank(storeId)){
            Account a = [SELECT Id, Industry, Name, CommercialSignLabel__c, Phone, BillingCity,BillingCountry,BillingPostalCode,BillingStreet, StoreId__c,StoreEmail__c 
            FROM Account
            WHERE StoreId__c =: storeId];
            System.debug(LoggingLevel.DEBUG,'account fields are' + a);
            return a;
        }
        else{
            return new Account();
        }
    }
}