force-app/main/default/objects/Account/fields/CommercialSignLabel__c.field-meta.xml
<CustomField>
    <fullName>CommercialSignLabel__c</fullName>
    <label>Enseigne Commerciale</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/StoreId__c.field-meta.xml
<CustomField>
    <fullName>StoreId__c</fullName>
    <externalId>true</externalId>
    <label>Code Magasin</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Store.recordType-meta.xml
<RecordType>
    <fullName>Store</fullName>
    <active>true</active>
    <label>Magasin</label>
</RecordType>

force-app/main/default/classes/Storelocator_Controller.cls
/**
* @author : Nicolas (Salesforce)
* @date : 20/04/2020
* @description : class to handle the Storelocator component
* @last modified date/comments :
*/
public without sharing class Storelocator_Controller {

    @AuraEnabled(cacheable=true)
    public static List<Account> searchStore(String searchTerms){
        System.debug('searchTerms: ' + searchTerms);
        if(String.isNotBlank(searchTerms) && String.isNotBlank(searchTerms.trim())){
            return [FIND :searchTerms IN ALL FIELDS RETURNING Account(Id,StoreId__c,Name,CommercialSignLabel__c,BillingStreet,BillingPostalCode,BillingCity WHERE RecordType.DeveloperName = 'Store' LIMIT 10)].get(0);
        }
        return new List<Account>();
    }
}