force-app/main/default/objects/Account/fields/Email_ID__c.field-meta.xml
<CustomField>
    <fullName>Email_ID__c</fullName>
    <caseSensitive>true</caseSensitive>
    <description>Contains the email adresse of Personal Account.
It&apos;s used as External ID to match with Commerce Cloud Clients.</description>
    <externalId>true</externalId>
    <label>Email ID</label>
    <type>Email</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Account/fields/PreferedStore__c.field-meta.xml
<CustomField>
    <fullName>PreferedStore__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Magasin Préféré</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Le record type du compte doit être &quot;Magasin&quot;</errorMessage>
        <filterItems>
            <field>Account.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>Store</value>
        </filterItems>
        <infoMessage>Le record type du compte doit être &quot;Magasin&quot;</infoMessage>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Clients - Magasin Préféré</relationshipLabel>
    <relationshipName>MagasinPrefere</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/StoreId__c.field-meta.xml
<CustomField>
    <fullName>StoreId__c</fullName>
    <externalId>true</externalId>
    <label>Code Magasin</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Case/fields/CDV__c.field-meta.xml
<CustomField>
    <fullName>CDV__c</fullName>
    <label>Cycle de vie (CDV)</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>CDV</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/CommerceCloudId__c.field-meta.xml
<CustomField>
    <fullName>CommerceCloudId__c</fullName>
    <label>CommerceCloud Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/ContactasGuest__c.field-meta.xml
<CustomField>
    <fullName>ContactasGuest__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Contact as Guest</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Case/fields/FirstName__c.field-meta.xml
<CustomField>
    <fullName>FirstName__c</fullName>
    <label>Prénom</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/FullName__c.field-meta.xml
<CustomField>
    <fullName>FullName__c</fullName>
    <description>Field used to track data used to create customer when he/she doesn&apos;t exists.</description>
    <label>Nom Complet</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/HomePhone__c.field-meta.xml
<CustomField>
    <fullName>HomePhone__c</fullName>
    <label>Home Phone</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Case/fields/IP__c.field-meta.xml
<CustomField>
    <fullName>IP__c</fullName>
    <label>IP</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/LastName__c.field-meta.xml
<CustomField>
    <fullName>LastName__c</fullName>
    <label>Nom</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/LoyaltyBirthdate__c.field-meta.xml
<CustomField>
    <fullName>LoyaltyBirthdate__c</fullName>
    <label>Date de naissance (FID)</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Case/fields/LoyaltyCardID__c.field-meta.xml
<CustomField>
    <fullName>LoyaltyCardID__c</fullName>
    <label>Numéro de la Carte U</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/LoyaltyCreationDate__c.field-meta.xml
<CustomField>
    <fullName>LoyaltyCreationDate__c</fullName>
    <label>Date de création Carte U</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Case/fields/LoyaltyFirstName__c.field-meta.xml
<CustomField>
    <fullName>LoyaltyFirstName__c</fullName>
    <label>Prénom (FID)</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/LoyaltyLastName__c.field-meta.xml
<CustomField>
    <fullName>LoyaltyLastName__c</fullName>
    <label>Nom (FID)</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/MobilePhone__c.field-meta.xml
<CustomField>
    <fullName>MobilePhone__c</fullName>
    <label>Mobile Phone</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Case/fields/NewsletterStatus__c.field-meta.xml
<CustomField>
    <fullName>NewsletterStatus__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Souscription Newsletter</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Case/fields/Phone__c.field-meta.xml
<CustomField>
    <fullName>Phone__c</fullName>
    <description>Field used to track data used to create customer when he/she doesn&apos;t exists.</description>
    <label>Téléphone</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Case/fields/RFM__c.field-meta.xml
<CustomField>
    <fullName>RFM__c</fullName>
    <label>Segmentation RFM</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>RFM</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Salutation__c.field-meta.xml
<CustomField>
    <fullName>Salutation__c</fullName>
    <label>Salutation</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Mme</fullName>
            </value>
            <value>
                <fullName>M.</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/SDC__c.field-meta.xml
<CustomField>
    <fullName>SDC__c</fullName>
    <label>Segmentation SDC</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>SDC</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/SessionStoreId__c.field-meta.xml
<CustomField>
    <fullName>SessionStoreId__c</fullName>
    <description>Field displayed in web-to-case and that contains the store number. The store number is external ID on store and is used to populate the Store field (Store__c)</description>
    <label>Session Store Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Store__c.field-meta.xml
<CustomField>
    <fullName>Store__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Contains the Store concerned by the case</description>
    <label>Magasin</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Le record type du compte doit être &quot;Magasin&quot;</errorMessage>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Magasin</value>
        </filterItems>
        <infoMessage>Le record type du compte doit être &quot;Magasin&quot;</infoMessage>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Tickets du Magasin</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/UserAgent__c.field-meta.xml
<CustomField>
    <fullName>UserAgent__c</fullName>
    <label>User Agent</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/VCA__c.field-meta.xml
<CustomField>
    <fullName>VCA__c</fullName>
    <label>Segmentation VCA</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>VCA</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/WorldlineId__c.field-meta.xml
<CustomField>
    <fullName>WorldlineId__c</fullName>
    <label>Worldline Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/CDV__c.field-meta.xml
<CustomField>
    <fullName>CDV__c</fullName>
    <inlineHelpText>Segmentation CDV (Cycle de vie) du porteur de la Carte U renseignée dans la fiche de l&apos;internaute connecté.</inlineHelpText>
    <label>Cycle de vie (CDV)</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>CDV</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/CommerceCloudId__c.field-meta.xml
<CustomField>
    <fullName>CommerceCloudId__c</fullName>
    <externalId>true</externalId>
    <label>CommerceCloud Id</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Contact/fields/LoyaltyBirthdate__c.field-meta.xml
<CustomField>
    <fullName>LoyaltyBirthdate__c</fullName>
    <label>Date de naissance (FID)</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Contact/fields/LoyaltyCardID__c.field-meta.xml
<CustomField>
    <fullName>LoyaltyCardID__c</fullName>
    <label>Numéro de carte active</label>
    <length>14</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/LoyaltyCreationDate__c.field-meta.xml
<CustomField>
    <fullName>LoyaltyCreationDate__c</fullName>
    <inlineHelpText>Date de la première saisie du bulletin d&apos;inscription au programme de fidélité U renseigné dans Claris de la Carte U renseigné dans la fiche de l&apos;internaute connecté.</inlineHelpText>
    <label>Date de création Carte U</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Contact/fields/LoyaltyFirstName__c.field-meta.xml
<CustomField>
    <fullName>LoyaltyFirstName__c</fullName>
    <label>Prénom (FID)</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/LoyaltyLastName__c.field-meta.xml
<CustomField>
    <fullName>LoyaltyLastName__c</fullName>
    <label>Nom (FID)</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/NewsletterStatus__c.field-meta.xml
<CustomField>
    <fullName>NewsletterStatus__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Souscription Newsletter</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/RFM__c.field-meta.xml
<CustomField>
    <fullName>RFM__c</fullName>
    <inlineHelpText>Segmentation RFM (Récense, Fréquence, Montant) du porteur de la Carte U renseignée dans la fiche de l&apos;internaute connecté.</inlineHelpText>
    <label>Segmentation RFM</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>RFM</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/SDC__c.field-meta.xml
<CustomField>
    <fullName>SDC__c</fullName>
    <label>Segmentation SDC</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>SDC</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/VCA__c.field-meta.xml
<CustomField>
    <fullName>VCA__c</fullName>
    <label>Segmentation VCA</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>VCA</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/WorldlineId__c.field-meta.xml
<CustomField>
    <fullName>WorldlineId__c</fullName>
    <label>Worldline Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PersonAccount/recordTypes/Client.recordType-meta.xml
<RecordType>
    <fullName>Client</fullName>
    <active>true</active>
    <label>Client</label>
</RecordType>

force-app/main/default/objects/User/fields/StoreId__c.field-meta.xml
<CustomField>
    <fullName>StoreId__c</fullName>
    <description>To store the store id of the user</description>
    <externalId>true</externalId>
    <label>StoreId</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/CaseTriggerHandler.cls
public with sharing class CaseTriggerHandler {

    public static final String PERSON_ACCOUNT_RECORDTYPE_DEVELOPER_NAME = 'Client';

    public static void beforeInsert(List<Case> cases) {
        //If no Contact/Account provided, it's populated is populated from based on SuppliedEmail. If no Contact found (Personal Account), new created
        Set<String> emailAddressesToParseCaseDescription = new Set<String>();
        emailAddressesToParseCaseDescription.addAll(Label.EMAIL_TO_CASE_EMAIL_ADDRESSES.split(';'));
        system.debug('Start point = '+cases.size());
        //Contains Supplied Emails for cases without Accounts + the list of Cases Id concerned by that email
        Map<String, Case> suppliedEmails = new Map<String, Case>();
        //We retrieve the record type for Personal Account
        Id pAccountRecordType = getPersonAccountRecordTypeId();
        system.debug('Account Record Type = '+pAccountRecordType);
        List<Account> accountsToUpdate = new List<Account>();
        Set<String> storeIds = new Set<String>();
        Map<String, Id> storesByStoreId = new Map<String, Id>();

        for (Case c : cases) {
            if (emailAddressesToParseCaseDescription.contains(c.SuppliedEmail) && c.Subject.endsWith('Demande liée au site') && !String.isEmpty(c.Description)) {
                String storeId = findStoreIdAttributeValue('Code du magasin : ', c.Description);
                if (storeId != ''){
                    storeIds.add(storeId);
                }
            }
        }

        if (!storeIds.isEmpty()) {
            storesByStoreId = getStoreIdsByExtStoreIds(storeIds);
        }

        for (Case c : cases){
            system.debug('Case = '+c.SuppliedEmail);
            String originalSuppliedEmail = c.SuppliedEmail;
            Boolean emailToCaseSourced = false;

            //manage email forwarding
            if(c.SuppliedEmail == Label.FORWARDING_SENDER_EMAIL && c.Subject == 'Contact au formulaire' && !String.isEmpty(c.Description)) {
                String senderEmail = c.Description.substringBetween('Adresse email de l\'émetteur : ', 'Nom et prénom de l\'émetteur :');
                String senderName = c.Description.substringBetween('Nom et prénom de l\'émetteur : ', 'Numéro de carte U de l\'émetteur :');
                String senderCard = c.Description.substringBetween('Numéro de carte U de l\'émetteur :', 'Téléphone :');
                String senderPhone = c.Description.substringBetween('Téléphone :', 'Objet du message :');
                String senderSubject = c.Description.substringBetween('Objet du message : ', 'Corps du message :');
                String senderDesc= c.Description.substringAfter('Corps du message :');

                if(!String.isEmpty(senderEmail)) c.SuppliedEmail = senderEmail.trim().replaceAll('(\\r|\\n)+', '');
                if(!String.isEmpty(senderName)) c.SuppliedName = senderName.trim().replaceAll('(\\r|\\n)+', '');
                if(!String.isEmpty(senderCard)) c.LoyaltyCardID__c = senderCard.trim().replaceAll('(\\r|\\n)+', '');
                if(!String.isEmpty(senderPhone)) c.SuppliedPhone = senderPhone.trim().replaceAll('(\\r|\\n)+', '');
                if(!String.isEmpty(senderSubject)) c.Subject = senderSubject.trim().replaceAll('(\\r|\\n)+', '');
                if(!String.isEmpty(senderDesc)) c.Description = senderDesc;
            } else if(emailAddressesToParseCaseDescription.contains(c.SuppliedEmail) && c.Subject.endsWith('Demande liée à la carte U') && !String.isEmpty(c.Description)) {
                String senderName = c.Description.substringBetween('Nom = ', 'E-mail = ');
                String senderEmail = c.Description.substringBetween('E-mail = ', 'Téléphone =');
                String senderPhone = c.Description.substringBetween('Téléphone = ', 'Commentaire =');
                String ip = c.Description.substringBetween('IP : ', 'User agent :');
                String UserAgent = c.Description.substringBetween('User agent : ', 'Code du magasin :');


                if(!String.isEmpty(senderEmail)) c.SuppliedEmail = senderEmail.trim().replaceAll('(\\r|\\n)+', '');
                if(!String.isEmpty(senderName)) c.SuppliedName = senderName.trim().replaceAll('(\\r|\\n)+', '');
                if(!String.isEmpty(senderPhone)) c.SuppliedPhone = senderPhone.trim().replaceAll('(\\r|\\n)+', '');
                if(!String.isEmpty(ip)) c.IP__c = ip.trim().replaceAll('(\\r|\\n)+', '');
                if(!String.isEmpty(UserAgent)) c.UserAgent__c = UserAgent.trim().replaceAll('(\\r|\\n)+', '');
            } else if(emailAddressesToParseCaseDescription.contains(c.SuppliedEmail) && c.Subject.endsWith('Demande liée au site') && !String.isEmpty(c.Description)) {
                String senderName = c.Description.substringBetween('Nom = ', 'E-mail = ');
                String senderEmail = c.Description.substringBetween('E-mail = ', 'Téléphone =');
                String senderPhone = c.Description.substringBetween('Téléphone = ', 'Commentaire =');
                String ip = c.Description.substringBetween('IP : ', 'User agent :');
                String UserAgent = c.Description.substringBetween('User agent : ', 'Code du magasin :');
                String storeId = findStoreIdAttributeValue('Code du magasin : ', c.Description);

                if(!String.isEmpty(senderEmail)) c.SuppliedEmail = senderEmail.trim().replaceAll('(\\r|\\n)+', '');
                if(!String.isEmpty(senderName)) c.SuppliedName = senderName.trim().replaceAll('(\\r|\\n)+', '');
                if(!String.isEmpty(senderPhone)) c.SuppliedPhone = senderPhone.trim().replaceAll('(\\r|\\n)+', '');
                if(!String.isEmpty(ip)) c.IP__c = ip.trim().replaceAll('(\\r|\\n)+', '');
                if(!String.isEmpty(UserAgent)) c.UserAgent__c = UserAgent.trim().replaceAll('(\\r|\\n)+', '');
                if(!String.isEmpty(storeId)){
                    if(storesByStoreId.containsKey(storeId)){
                        c.Store__c = storesByStoreId.get(storeId);
                    }
                }

                c.AccountId = null;
                c.ContactId = null;
                emailToCaseSourced = true;
            }

            //Retrive list of emails to lookup in Personal Account List
            if ((c.AccountId == null && c.ContactId == null && c.SuppliedEmail != '') || emailToCaseSourced)
            {
                if (!suppliedEmails.containsKey(c.SuppliedEmail)){
                    //We add the first case encountered (required, when we need to create the Client)
                    suppliedEmails.put(c.SuppliedEmail, c);
                }
            }
        }

        //Retrive Matching Personal Accounts form Database
        Map<String,Account> myClients = getAccountByEmail(suppliedEmails.keySet(), pAccountRecordType);
        system.debug('myClients initial Size = '+myClients.size());
        //List of new Clients (the ones missing for "myClients")
        List<Account> newClients = new List<Account>();

        //Check missing emails (define new Personal Accounts to create) + get case information with it
        for (String emailValue : suppliedEmails.keySet()){
            if (myClients.get(emailValue) == null){
                //We retrieve the first occurence of that email to create the new Account
                Account theClient = createNewAccountFromCase(suppliedEmails.get(emailValue), pAccountRecordType);

                //Add to the list of New clients
                newClients.add(theClient);
            }
        }
        system.debug('NewClients Size = '+newClients.size());
        //We create the new clients
        database.insert(newClients,false);

        //We retrieve information we are missing --update our list of Clients by upserting the new Clients
        myClients = getAccountByEmail(suppliedEmails.keySet(), pAccountRecordType);
        system.debug('myClients final Size = '+myClients.size());

        //We update Cases with missing informations
        for (Case c : cases){
            if (c.AccountId == null && c.ContactId == null && c.SuppliedEmail != '' && myClients.containsKey(c.SuppliedEmail))
            {
                //Update PersonAccount (client) and associated Contact
                c.AccountId = myClients.get(c.SuppliedEmail).Id;
                c.ContactId = myClients.get(c.SuppliedEmail).PersonContactId;
            }

            if (myClients.containsKey(c.SuppliedEmail)) {
                if (myClients.get(c.SuppliedEmail).LoyaltyCardID__pc == null && c.LoyaltyCardID__c != null) {
                    accountsToUpdate.add(new Account(Id = myClients.get(c.SuppliedEmail).Id, LoyaltyCardID__pc = c.LoyaltyCardID__c));
                }
            }
        }

        if (!accountsToUpdate.isEmpty()) {
            update accountsToUpdate;
        }
    }

    private static Map<String, Account> getAccountByEmail(Set<String> listOfEmails, Id recordTypeOfAccount){
        //Retrive Matching Personal Accounts form Database
        Map<String,Account> finalList = new Map<String,Account>();
        Map<Id,Account> databaseAccounts = new Map<Id, Account>([SELECT Id, Email_ID__c, PersonContactId, LoyaltyCardID__pc
        FROM Account WHERE Email_ID__c IN :listOfEmails AND RecordTypeId = :recordTypeOfAccount]);
        //Populate our map of Email -> Account
        for (Id vId : databaseAccounts.keySet()){
            finalList.put(databaseAccounts.get(vId).Email_ID__c, databaseAccounts.get(vId));
        }

        return finalList;
    }

    private static Account createNewAccountFromCase(Case c, Id accountRecordType){
        system.debug('c.Origin = '+string.valueOf(c.Origin));
        system.debug('c.FullName__c = '+string.valueOf(c.FullName__c));
        system.debug('c.LastName__c = '+string.valueOf(c.LastName__c));
        system.debug('c.FirstName__c = '+string.valueOf(c.FirstName__c));
        system.debug('c.SuppliedName = '+string.valueOf(c.SuppliedName));

        if (c.Origin == 'Email') {
            // Pour le email-2-case on est forcement en guest.
            c.ContactasGuest__c = true;

            //Cas specifique du Email-to-case (et non pas à la reprise de données)
            if (String.isBlank(c.FullName__c) && !String.isBlank(c.SuppliedName)){
                c.FullName__c = c.SuppliedName;
            }
        }

        Account myAccount = new Account (
                CDV__pc=c.CDV__c,
                CommerceCloudId__pc=c.CommerceCloudId__c,
                FirstName=c.FirstName__c,
                LastName=c.ContactasGuest__c ? c.FullName__c : c.LastName__c,
                LoyaltyBirthdate__pc=c.LoyaltyBirthdate__c,
                LoyaltyCardID__pc=c.LoyaltyCardID__c,
                LoyaltyCreationDate__pc=c.LoyaltyCreationDate__c,
                LoyaltyFirstName__pc=c.LoyaltyFirstName__c,
                LoyaltyLastName__pc=c.LoyaltyLastName__c,
                NewsletterStatus__pc=c.NewsletterStatus__c,
                PersonEmail=c.SuppliedEmail,
                PersonMobilePhone=c.MobilePhone__c,
                PersonHomePhone=c.HomePhone__c,
                Phone=c.Phone__c,
                //PreferedStore__c='SessionStoreId__c base',
                RFM__pc=c.RFM__c,
                RecordTypeId=accountRecordType,
                SDC__pc=c.SDC__c,
                Salutation=c.Salutation__c,
                VCA__pc=c.VCA__c,
                WorldlineId__pc=c.WorldlineId__c
        );

        return myAccount;
    }

    /**
     * @author Denys Taldykin
     * @date April 27, 2023
     * @name findStoreIdAttributeValue
     * @description method to extract StoreId attribute value
     * @param startText String
     * @param searchString String
     * @return String
     */
    public static String findStoreIdAttributeValue(String startText, String searchString) {
        String textFound = '';
        Integer startIndex;
        Integer endIndex = 6 + startText.length();

        if (searchString.contains(startText)) {
            startIndex = searchString.indexOf(startText);

            textFound = searchString.mid(startIndex, endIndex);
            textFound = textFound.replace(startText, '').trim();
        }

        return textFound;
    }

    /**
     * @author Denys Taldykin
     * @date April 27, 2023
     * @name getStoreIdsByExtStoreIds
     * @description method to query Account Ids by ext StoreId__c map
     * @param storeIds Set<String>
     * @return Map<String, Id>
     */
    public static Map<String, Id> getStoreIdsByExtStoreIds(Set<String> storeIds) {
        Map<String, Id> storeIdsByExtStoreIds = new Map<String, Id>();
        Set<String> storeExtIds = new Set<String>();
        List<Account> storeAccounts;

        storeAccounts = [SELECT Id, StoreId__c FROM Account WHERE StoreId__c IN :storeIds AND StoreId__c != NULL];

        for (Account a : storeAccounts) {
            storeIdsByExtStoreIds.put(a.StoreId__c, a.Id);
        }

        return storeIdsByExtStoreIds;
    }

    private static Id getPersonAccountRecordTypeId(){
        return Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get(PERSON_ACCOUNT_RECORDTYPE_DEVELOPER_NAME).getRecordTypeId();
    }
}