force-app/main/default/objects/Account/fields/IsActive__c.field-meta.xml
<CustomField>
    <fullName>IsActive__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/StoreId__c.field-meta.xml
<CustomField>
    <fullName>StoreId__c</fullName>
    <externalId>true</externalId>
    <label>Code Magasin</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/CustomerSlot__c/CustomerSlot__c.object-meta.xml
<CustomObject>
    <description>Object containing customer slots (booked, canceled or completed)</description>
    <label>Réservation client</label>
    <nameField>
        <displayFormat>BN{000000}</displayFormat>
        <label>Booking number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Réservations client</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/CustomerSlot__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Store concerned by the customer slot</description>
    <label>Store</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Customer slots</relationshipLabel>
    <relationshipName>CustomerSlots</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CustomerSlot__c/fields/Duration__c.field-meta.xml
<CustomField>
    <fullName>Duration__c</fullName>
    <description>Duration of the customer slot in minutes</description>
    <formula>Slot__r.Duration__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Duration (in minutes)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/CustomerSlot__c/fields/ExpectedStartDatetime__c.field-meta.xml
<CustomField>
    <fullName>ExpectedStartDatetime__c</fullName>
    <description>expected arrival time based on currently booked slots</description>
    <label>Expected Start date/time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/CustomerSlot__c/fields/ProvidedEmail__c.field-meta.xml
<CustomField>
    <fullName>ProvidedEmail__c</fullName>
    <description>Email provided by customer (set in customer slot form)</description>
    <label>Provided Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/CustomerSlot__c/fields/ProvidedFirstName__c.field-meta.xml
<CustomField>
    <fullName>ProvidedFirstName__c</fullName>
    <description>Provided first name of the customer (set in customer slot form)</description>
    <label>Provided First name</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CustomerSlot__c/fields/ProvidedLastName__c.field-meta.xml
<CustomField>
    <fullName>ProvidedLastName__c</fullName>
    <description>Provided last name of the customer (set in customer slot form)</description>
    <label>Provided Last name</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CustomerSlot__c/fields/ProvidedNumberOfPersons__c.field-meta.xml
<CustomField>
    <fullName>ProvidedNumberOfPersons__c</fullName>
    <description>Provided number of total physical persons coming to the store (set in customer slot form)</description>
    <label>Provided number of persons</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/CustomerSlot__c/fields/Slot__c.field-meta.xml
<CustomField>
    <fullName>Slot__c</fullName>
    <description>Parent slot concerned by this customer slot</description>
    <label>Slot</label>
    <referenceTo>Slot__c</referenceTo>
    <relationshipLabel>Customer slots</relationshipLabel>
    <relationshipName>CustomerSlots</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/CustomerSlot__c/fields/StartDatetime__c.field-meta.xml
<CustomField>
    <fullName>StartDatetime__c</fullName>
    <description>Starting date and time of the customer slot</description>
    <formula>Slot__r.StartDatetime__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Starting date/time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/CustomerSlot__c/fields/UUID__c.field-meta.xml
<CustomField>
    <fullName>UUID__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <label>UUID</label>
    <length>100</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/QueueBustingConfig__c/QueueBustingConfig__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Contains custom settings used to in the Queue busting application</description>
    <label>Queue busting App Config</label>
</CustomObject>

force-app/main/default/objects/QueueBustingConfig__c/fields/DefaultSlotDuration__c.field-meta.xml
<CustomField>
    <fullName>DefaultSlotDuration__c</fullName>
    <defaultValue>60</defaultValue>
    <description>Contains the default duration (in minutes) for slots</description>
    <inlineHelpText>Contains the default duration (in minutes) for slots</inlineHelpText>
    <label>Default slot duration (in minutes)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/QueueBustingConfig__c/fields/isCheckCustomerSlotDaysEnabled__c.field-meta.xml
<CustomField>
    <fullName>isCheckCustomerSlotDaysEnabled__c</fullName>
    <defaultValue>false</defaultValue>
    <description>define if we execute the timeframe check when a guest user try to create a customer slot</description>
    <label>isCheckCustomerSlotDaysEnabled</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/QueueBustingConfig__c/fields/NumberOfDaysBeforeToCheck__c.field-meta.xml
<CustomField>
    <fullName>NumberOfDaysBeforeToCheck__c</fullName>
    <description>Number of days before a relative slot to check if a client has booked a slot</description>
    <label>NumberOfDaysBeforeToCheck</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/QueueBustingConfig__c/fields/NumWeeksGeneratedSlots__c.field-meta.xml
<CustomField>
    <fullName>NumWeeksGeneratedSlots__c</fullName>
    <defaultValue>4</defaultValue>
    <description>Contains the number of weeks that is generated from recurring slots</description>
    <inlineHelpText>Contains the number of weeks that is generated from recurring slots</inlineHelpText>
    <label>Nb Weeks for recurring slot</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/reCaptcha__c/reCaptcha__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>reCaptcha</label>
</CustomObject>

force-app/main/default/objects/reCaptcha__c/fields/isReCaptchaEnabled__c.field-meta.xml
<CustomField>
    <fullName>isReCaptchaEnabled__c</fullName>
    <defaultValue>true</defaultValue>
    <label>isReCaptchaEnabled</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/reCaptcha__c/fields/SecretKey__c.field-meta.xml
<CustomField>
    <fullName>SecretKey__c</fullName>
    <label>Secret Key</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/reCaptcha__c/fields/SiteKey__c.field-meta.xml
<CustomField>
    <fullName>SiteKey__c</fullName>
    <label>Site Key</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RecurringSlot__c/RecurringSlot__c.object-meta.xml
<CustomObject>
    <description>Object containing recurring slots definition. Represent typical daily slot configuration.</description>
    <label>Créneau récurrent</label>
    <nameField>
        <displayFormat>RS{00000}</displayFormat>
        <label>Recurring slot number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Créneaux récurrents</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/RecurringSlot__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <description>Store concerned by the recurring slot</description>
    <label>Store</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Recurring slots</relationshipLabel>
    <relationshipName>RecurringSlots</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/RecurringSlot__c/fields/AvailablePositions__c.field-meta.xml
<CustomField>
    <fullName>AvailablePositions__c</fullName>
    <description>Number of available positions (number of customer that can enter) for each slots generated by this recurrence</description>
    <label>Available positions</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/RecurringSlot__c/fields/Duration__c.field-meta.xml
<CustomField>
    <fullName>Duration__c</fullName>
    <defaultValue>$Setup.QueueBustingConfig__c.DefaultSlotDuration__c</defaultValue>
    <description>Duration of the slots created by this recurrence in minutes</description>
    <label>Duration (in minutes)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/RecurringSlot__c/fields/EndTime__c.field-meta.xml
<CustomField>
    <fullName>EndTime__c</fullName>
    <description>Define the ending time of the slot</description>
    <inlineHelpText>Define the ending time of the slot</inlineHelpText>
    <label>End Time</label>
    <required>true</required>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/RecurringSlot__c/fields/IsActive__c.field-meta.xml
<CustomField>
    <fullName>IsActive__c</fullName>
    <defaultValue>true</defaultValue>
    <description>True when the recurring slot is active</description>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/RecurringSlot__c/fields/RecurrenceDays__c.field-meta.xml
<CustomField>
    <fullName>RecurrenceDays__c</fullName>
    <description>Contains list of week days for which this recurrence is applicable</description>
    <label>Recurrence days</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Monday</fullName>
            </value>
            <value>
                <fullName>Tuesday</fullName>
            </value>
            <value>
                <fullName>Wednesday</fullName>
            </value>
            <value>
                <fullName>Thursday</fullName>
            </value>
            <value>
                <fullName>Friday</fullName>
            </value>
            <value>
                <fullName>Saturday</fullName>
            </value>
            <value>
                <fullName>Sunday</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/RecurringSlot__c/fields/StartDatetime__c.field-meta.xml
<CustomField>
    <fullName>StartDatetime__c</fullName>
    <description>Date and time from which the recurrence will start</description>
    <label>Starting date/time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/RecurringSlot__c/fields/StartTime__c.field-meta.xml
<CustomField>
    <fullName>StartTime__c</fullName>
    <description>Define the starting time of the slot</description>
    <inlineHelpText>Define the starting time of the slot</inlineHelpText>
    <label>Start Time</label>
    <required>true</required>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/Slot__c/Slot__c.object-meta.xml
<CustomObject>
    <description>Object containing final slots for stores.</description>
    <label>Créneau</label>
    <nameField>
        <displayFormat>S{00000}</displayFormat>
        <label>Slot number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Créneaux</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Slot__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <description>Store concerned by the slot</description>
    <label>Store</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Slots</relationshipLabel>
    <relationshipName>Slots</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Slot__c/fields/AvailablePositions__c.field-meta.xml
<CustomField>
    <fullName>AvailablePositions__c</fullName>
    <description>Number of available positions (number of customer that can enter) for this slot</description>
    <formula>RecurringSlot__r.AvailablePositions__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Available positions</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Slot__c/fields/Duration__c.field-meta.xml
<CustomField>
    <fullName>Duration__c</fullName>
    <description>Duration of the slot in minutes</description>
    <formula>RecurringSlot__r.Duration__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Duration (in minutes)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Slot__c/fields/IsActive__c.field-meta.xml
<CustomField>
    <fullName>IsActive__c</fullName>
    <defaultValue>true</defaultValue>
    <description>True when the slot is active</description>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Slot__c/fields/RecurringSlot__c.field-meta.xml
<CustomField>
    <fullName>RecurringSlot__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Recurring slot concerned by the slot</description>
    <label>Recurring slot</label>
    <referenceTo>RecurringSlot__c</referenceTo>
    <relationshipLabel>Slots</relationshipLabel>
    <relationshipName>Slots</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Slot__c/fields/StartDatetime__c.field-meta.xml
<CustomField>
    <fullName>StartDatetime__c</fullName>
    <description>Starting date and time of the slot</description>
    <label>Starting date/time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/User/fields/StoreId__c.field-meta.xml
<CustomField>
    <fullName>StoreId__c</fullName>
    <description>To store the store id of the user</description>
    <externalId>true</externalId>
    <label>StoreId</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/TestDataFactory.cls
/**
* @author : Nicolas (Salesforce)
* @date : 20/04/2020
* @description : class to handle the CustomerSlots
* @last modified date/comments :
*/
@isTest
public class TestDataFactory {

    /*Create Running User*/
    public static User createRunningUser(){
        Profile p = [SELECT Id FROM Profile WHERE Name = 'System Administrator'];
        String key = EncodingUtil.convertToHex(crypto.generateAesKey(128));
        String userEmailPrefix = key.substring(0, 10);
        
        User user = new User(Alias = 'test', Email =  userEmailPrefix+'@test.fr',
                             EmailEncodingKey = 'UTF-8', LastName = 'Testing', LanguageLocaleKey = 'en_US',
                             LocaleSidKey = 'en_US', ProfileId = p.Id,
                             TimeZoneSidKey = 'Europe/Paris', UserName = userEmailPrefix+'@test.fr');
        insert user;
        return user;
    }

    /*Create Accounts*/
    public static List<Account> createAccount(integer nb) {
        List<Account> accs = new List<Account>();
        for(Integer i=0;i<nb;i++) {
            accs.add(new Account(Name='Test Account' + i,StoreId__c= '' + i));
        }
        insert accs;
        return accs;
    }
    /*Create RecurringSlot__c*/
    public static List<RecurringSlot__c> createRecurringSlot(String accId,integer nb) {
        List<RecurringSlot__c> rs = new List<RecurringSlot__c>();
        Time startTime = Time.newInstance(9, 0, 0, 0);
        for(Integer i=0;i<nb;i++) {
            rs.add(new RecurringSlot__c(Account__c=accId,isActive__c=true,RecurrenceDays__c='Monday;Tuesday;Wednesday;Thursday;Friday;Saturday;Sunday',
                        StartDatetime__c=Datetime.now(),AvailablePositions__c=10,Duration__c=60,StartTime__c=startTime,EndTime__c=startTime.addHours(8)));
        }
        insert rs;
        return rs;
    }
    /*Create Slot__c*/
    public static List<Slot__c> createSlot(String accId,String recurringSlotId,integer nb) {
        List<Slot__c> s = new List<Slot__c>();
        for(Integer i=0;i<nb;i++) {
            s.add(new Slot__c(Account__c=accId,RecurringSlot__c=recurringSlotId,StartDatetime__c=Datetime.now()));
        }
        insert s;
        return s;
    }
    /*Create CustomerSlot__c*/
    public static List<CustomerSlot__c> createCustomerSlot(String accId,String slotId,integer nb) {
        List<CustomerSlot__c> cs = new List<CustomerSlot__c>();
        Datetime dt = Datetime.now();
        for(Integer i=0;i<nb;i++) {
            cs.add(new CustomerSlot__c(Account__c=accId,Slot__c=slotId,
                                       ProvidedFirstName__c='Test ' + i,
                                       ProvidedLastName__c='Test ' + i,
                                       ProvidedEmail__c = 'test' + i + '@testclient.com',
                                       ProvidedNumberOfPersons__c=1,
                                       ExpectedStartDatetime__c = dt,
                                       UUID__c = GuidUtil.NewGuid()));
        }
        insert cs;
        return cs;
    }

    public static Slot__c createUnitTestCaseSlot() {
        Account a = createAccount(1).get(0);
        RecurringSlot__c rs = createRecurringSlot(a.Id,1).get(0);
        return createSlot(a.Id,rs.Id,1).get(0);
    }

    public static CustomerSlot__c createUnitTestCase() {
        Account a = createAccount(1).get(0);
        RecurringSlot__c rs = createRecurringSlot(a.Id,1).get(0);
        Slot__c s = createSlot(a.Id,rs.Id,1).get(0);
        return createCustomerSlot(a.Id,s.Id,1).get(0);
    }

    public static void createCS(){
        insert new reCaptcha__c(
            isReCaptchaEnabled__c=true,
            SecretKey__c='23456789',
            SiteKey__c='234567IUHG');
        insert new QueueBustingConfig__c(
            DefaultSlotDuration__c=60,
            NumWeeksGeneratedSlots__c=1,
            isCheckCustomerSlotDaysEnabled__c = true,
            NumberOfDaysBeforeToCheck__c = 0,
            NumberOfDaysAfterToCheck__c = 2,
            isGeneratePdfEnabled__c = true);
    }

}