force-app/main/default/objects/Account/fields/IsActive__c.field-meta.xml
<CustomField>
    <fullName>IsActive__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/StoreId__c.field-meta.xml
<CustomField>
    <fullName>StoreId__c</fullName>
    <externalId>true</externalId>
    <label>Code Magasin</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Slot__c/Slot__c.object-meta.xml
<CustomObject>
    <description>Object containing final slots for stores.</description>
    <label>Créneau</label>
    <nameField>
        <displayFormat>S{00000}</displayFormat>
        <label>Slot number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Créneaux</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Slot__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <description>Store concerned by the slot</description>
    <label>Store</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Slots</relationshipLabel>
    <relationshipName>Slots</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Slot__c/fields/AvailablePositions__c.field-meta.xml
<CustomField>
    <fullName>AvailablePositions__c</fullName>
    <description>Number of available positions (number of customer that can enter) for this slot</description>
    <formula>RecurringSlot__r.AvailablePositions__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Available positions</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Slot__c/fields/IsActive__c.field-meta.xml
<CustomField>
    <fullName>IsActive__c</fullName>
    <defaultValue>true</defaultValue>
    <description>True when the slot is active</description>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Slot__c/fields/RemainingPositions__c.field-meta.xml
<CustomField>
    <fullName>RemainingPositions__c</fullName>
    <description>Number of remaining positions (number of customer that can still book) for this slot</description>
    <formula>AvailablePositions__c - BookedPositions__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Remaining positions</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Slot__c/fields/StartDatetime__c.field-meta.xml
<CustomField>
    <fullName>StartDatetime__c</fullName>
    <description>Starting date and time of the slot</description>
    <label>Starting date/time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/User/fields/StoreId__c.field-meta.xml
<CustomField>
    <fullName>StoreId__c</fullName>
    <description>To store the store id of the user</description>
    <externalId>true</externalId>
    <label>StoreId</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/TimeSlotManager.cls
/**
* @author : 
* @date : 20/04/2020
* @description : class to handle time slot (guest page)
* @last modified date/comments :
*/
public without sharing class TimeSlotManager {
    //without sharing due to usage as guest user (better than open sharing)
    
    //(cacheable=true)
    @AuraEnabled(cacheable=false)
    public static List<HoursWrapper> getSlots( String storeId,Integer dateOffset ) {
        Integer STARTTIME = 8;
        Integer LENGTH_OF_DAY = 8;
        System.debug(LoggingLevel.DEBUG,'storeId: ' + storeId + ' dateOffset: ' + dateOffset );
        Date d = Date.today();
        Date startdate = d.addDays(dateOffset);
        Date enddate = startdate.addDays(7);
        System.debug(LoggingLevel.DEBUG,'startDate: ' + startdate + ' enddate: ' + enddate);

        List<HoursWrapper> hourWrapperList = new List<HoursWrapper>();
        Map<String,List<SlotWrapper>> timeSlotMap = new Map<String, List<SlotWrapper>>();

        List<Slot__c> slots = [SELECT Id, Account__r.StoreId__c, StartDatetime__c, RemainingPositions__c, AvailablePositions__c,IsActive__c
                                        FROM Slot__c 
                                        WHERE StartDatetime__c > :startdate AND StartDatetime__c < :enddate 
                                          AND Account__r.StoreId__c = :storeId
                                          AND IsActive__c = true
                                        ORDER BY StartDatetime__c];

        String lastDay = '';
        String lastHour = '';
        String lastMinutes = '';
        for(Slot__c s : slots){ 
            //Create SlotWrapper
            SlotWrapper sw = new SlotWrapper();
            sw.id = s.Id;
            sw.day = s.StartDatetime__c.format('d');
            sw.hour = s.StartDatetime__c.format('HH');
            sw.minutes = s.StartDatetime__c.format('mm');
            sw.remainingPositions = Integer.valueOf(s.RemainingPositions__c);
            sw.defaultPositions = Integer.valueOf(s.AvailablePositions__c);
            sw.StartDatetime = s.StartDatetime__c;

            // Get value the first of hour of slot --> aggregate by hour
            /*if(lastDay + lastHour != sw.day + sw.hour){
                lastMinutes = sw.minutes;
            }
            String timeS = sw.hour + ':' + lastMinutes;
            lastDay = sw.day;
            lastHour = sw.hour;*/
            String timeS = sw.hour + ':00';

            // If the key exists add record to it
            if (timeSlotMap.containsKey(timeS)){
                    timeSlotMap.get(timeS).add(sw);
            } 
            // If the key does not exists create it and add record
            else {
                timeSlotMap.put(timeS, new  List <SlotWrapper> { sw });
            }
        }

        System.debug(LoggingLevel.DEBUG,'Map: ' + timeSlotMap);

        for (String key : timeSlotMap.keySet()) {
            HoursWrapper hoursWrap = new HoursWrapper();
            hoursWrap.hour = String.valueof(key);
            System.debug(LoggingLevel.DEBUG,'yyyy: ' + timeSlotMap.get(key));           
            hoursWrap.slots = timeSlotMap.get(key);
            hourWrapperList.add(hoursWrap);
        }          
        System.debug(LoggingLevel.DEBUG,'Map2: ' + hourWrapperList);   
        hourWrapperList.sort();

        return hourWrapperList;
    }

    public class HoursWrapper implements Comparable {
        @AuraEnabled
        public String hour {get; set;}
        @AuraEnabled
        public List<SlotWrapper> slots {get; set;}

        public Integer compareTo(Object other) {
            String compareToHour = ((HoursWrapper)other).hour;
            return Integer.valueOf(hour.left(2)) - Integer.valueOf(compareToHour.left(2));
        }
    }
    public class SlotWrapper {
        @AuraEnabled
        public String id {get; set;}
        @AuraEnabled
        public String day {get; set;}
        @AuraEnabled
        public String hour {get; set;}
        @AuraEnabled
        public String minutes {get; set;}
        @AuraEnabled
        public Integer remainingPositions {get; set;}
        @AuraEnabled
        public Integer defaultPositions {get; set;}
        @AuraEnabled
        public Datetime StartDatetime {get; set;}
    }     
}