force-app/main/default/objects/Account/fields/IsActive__c.field-meta.xml
<CustomField>
    <fullName>IsActive__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/IsIncludedOnlineBooking__c.field-meta.xml
<CustomField>
    <fullName>IsIncludedOnlineBooking__c</fullName>
    <defaultValue>false</defaultValue>
    <description>True when the store is included in the online booking system for queue management</description>
    <label>Online-booking store</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/QueueBustingConfig__c/QueueBustingConfig__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Contains custom settings used to in the Queue busting application</description>
    <label>Queue busting App Config</label>
</CustomObject>

force-app/main/default/objects/QueueBustingConfig__c/fields/NumWeeksGeneratedSlots__c.field-meta.xml
<CustomField>
    <fullName>NumWeeksGeneratedSlots__c</fullName>
    <defaultValue>4</defaultValue>
    <description>Contains the number of weeks that is generated from recurring slots</description>
    <inlineHelpText>Contains the number of weeks that is generated from recurring slots</inlineHelpText>
    <label>Nb Weeks for recurring slot</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/RecurringSlot__c/RecurringSlot__c.object-meta.xml
<CustomObject>
    <description>Object containing recurring slots definition. Represent typical daily slot configuration.</description>
    <label>Créneau récurrent</label>
    <nameField>
        <displayFormat>RS{00000}</displayFormat>
        <label>Recurring slot number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Créneaux récurrents</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/RecurringSlot__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <description>Store concerned by the recurring slot</description>
    <label>Store</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Recurring slots</relationshipLabel>
    <relationshipName>RecurringSlots</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/RecurringSlot__c/fields/AvailablePositions__c.field-meta.xml
<CustomField>
    <fullName>AvailablePositions__c</fullName>
    <description>Number of available positions (number of customer that can enter) for each slots generated by this recurrence</description>
    <label>Available positions</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/RecurringSlot__c/fields/IsActive__c.field-meta.xml
<CustomField>
    <fullName>IsActive__c</fullName>
    <defaultValue>true</defaultValue>
    <description>True when the recurring slot is active</description>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/RecurringSlot__c/fields/RecurrenceDays__c.field-meta.xml
<CustomField>
    <fullName>RecurrenceDays__c</fullName>
    <description>Contains list of week days for which this recurrence is applicable</description>
    <label>Recurrence days</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Monday</fullName>
            </value>
            <value>
                <fullName>Tuesday</fullName>
            </value>
            <value>
                <fullName>Wednesday</fullName>
            </value>
            <value>
                <fullName>Thursday</fullName>
            </value>
            <value>
                <fullName>Friday</fullName>
            </value>
            <value>
                <fullName>Saturday</fullName>
            </value>
            <value>
                <fullName>Sunday</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/RecurringSlot__c/fields/StartDatetime__c.field-meta.xml
<CustomField>
    <fullName>StartDatetime__c</fullName>
    <description>Date and time from which the recurrence will start</description>
    <label>Starting date/time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/classes/Batch_SlotGenerate.cls
/**
* @author : Nicolas Greard (Salesforce)
* @date : 2/5/2020
* @description : class to generate slot based on account config
* @last modified date/comments :
*/
global class Batch_SlotGenerate implements Database.Batchable<sObject>,schedulable{
    public Integer BATCH_SIZE = 200;
    public Date firstDayOfWeek = Date.newInstance(2020,5,4);
    /**
    * @description start
    * @param bc : context
    * @return query
    */
    global Database.QueryLocator start(Database.BatchableContext bc) {
        return Database.getQueryLocator(
            'SELECT Id,Account__c,AvailablePositions__c,IsActive__c,RecurrenceDays__c,StartDatetime__c,Account__r.IsIncludedOnlineBooking__c FROM RecurringSlot__c WHERE IsActive__c = true AND Account__r.IsIncludedOnlineBooking__c = true'
        );
    }

    global void execute(Database.BatchableContext bc, List<RecurringSlot__c> rss){
        List<String> rsIds = new List<String>();
        for(RecurringSlot__c rs : rss){
            rsIds.add(rs.Id);
        }
        System.debug(LoggingLevel.DEBUG,'rsIds:' + rsIds.size());
        if(!rsIds.isEmpty()){
            Integer numOfWeeks = Integer.valueOf(QueueBustingConfig__c.getInstance().NumWeeksGeneratedSlots__c);
            GenerateSlots_Service.generateSlotsFromRecurringSlotsIds(rsIds,numOfWeeks - 1);
        }
    }

    global void finish(Database.BatchableContext bc){
    }
    
    /**
    * @description scheduler
    * @param ctx : context
    */
    global void execute(SchedulableContext ctx){
        database.executebatch(new Batch_SlotGenerate(),BATCH_SIZE);
    }
}