force-app/main/default/objects/Account/fields/IsIncludedOnlineBooking__c.field-meta.xml
<CustomField>
    <fullName>IsIncludedOnlineBooking__c</fullName>
    <defaultValue>false</defaultValue>
    <description>True when the store is included in the online booking system for queue management</description>
    <label>Online-booking store</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/StoreCustomerCount__c.field-meta.xml
<CustomField>
    <fullName>StoreCustomerCount__c</fullName>
    <defaultValue>0</defaultValue>
    <description>To store realtime customer count in the store</description>
    <label>Store Customer Count</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/Batch_StoreResetCounter.cls
/**
* @author : Nicolas Greard (Salesforce)
* @date : 16/06/2020
* @description : class to handle the account header
* @last modified date/comments :
*/
global with sharing class Batch_StoreResetCounter implements Database.Batchable<sObject>,schedulable {
    public Integer BATCH_SIZE = 200;

    /**
    * @description start
    * @param bc : context
    * @return query
    */
    global Database.QueryLocator start(Database.BatchableContext bc) {
        return Database.getQueryLocator(
            'SELECT Id,StoreCustomerCount__c,IsIncludedOnlineBooking__c FROM Account WHERE IsIncludedOnlineBooking__c = true AND StoreCustomerCount__c > 0'
        );
    }

    global void execute(Database.BatchableContext bc, List<Account> accs){
        for(Account a : accs){
            a.StoreCustomerCount__c = 0;
        }

        System.debug(LoggingLevel.DEBUG,'accs: ' + accs.size());
        if(!accs.isEmpty()){
            update accs;
        }
    }

    global void finish(Database.BatchableContext bc){
    }
    
    /**
    * @description scheduler
    * @param ctx : context
    */
    global void execute(SchedulableContext ctx){
        database.executebatch(new Batch_StoreResetCounter(),BATCH_SIZE);
    }
}