force-app/main/default/objects/Account/fields/Position__c.field-meta.xml
<CustomField>
    <fullName>Position__c</fullName>
    <label>Position</label>
    <scale>15</scale>
    <type>Location</type>
</CustomField>

force-app/main/default/objects/Account/fields/StoreId__c.field-meta.xml
<CustomField>
    <fullName>StoreId__c</fullName>
    <externalId>true</externalId>
    <label>Code Magasin</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/CustomerSlot__c/CustomerSlot__c.object-meta.xml
<CustomObject>
    <description>Object containing customer slots (booked, canceled or completed)</description>
    <label>Réservation client</label>
    <nameField>
        <displayFormat>BN{000000}</displayFormat>
        <label>Booking number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Réservations client</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/CustomerSlot__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Store concerned by the customer slot</description>
    <label>Store</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Customer slots</relationshipLabel>
    <relationshipName>CustomerSlots</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CustomerSlot__c/fields/ExpectedStartDatetime__c.field-meta.xml
<CustomField>
    <fullName>ExpectedStartDatetime__c</fullName>
    <description>expected arrival time based on currently booked slots</description>
    <label>Expected Start date/time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/CustomerSlot__c/fields/Position__c.field-meta.xml
<CustomField>
    <fullName>Position__c</fullName>
    <label>Position</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/CustomerSlot__c/fields/ProvidedEmail__c.field-meta.xml
<CustomField>
    <fullName>ProvidedEmail__c</fullName>
    <description>Email provided by customer (set in customer slot form)</description>
    <label>Provided Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/CustomerSlot__c/fields/ProvidedFirstName__c.field-meta.xml
<CustomField>
    <fullName>ProvidedFirstName__c</fullName>
    <description>Provided first name of the customer (set in customer slot form)</description>
    <label>Provided First name</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CustomerSlot__c/fields/ProvidedLastName__c.field-meta.xml
<CustomField>
    <fullName>ProvidedLastName__c</fullName>
    <description>Provided last name of the customer (set in customer slot form)</description>
    <label>Provided Last name</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CustomerSlot__c/fields/ProvidedNumberOfPersons__c.field-meta.xml
<CustomField>
    <fullName>ProvidedNumberOfPersons__c</fullName>
    <description>Provided number of total physical persons coming to the store (set in customer slot form)</description>
    <label>Provided number of persons</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/CustomerSlot__c/fields/Slot__c.field-meta.xml
<CustomField>
    <fullName>Slot__c</fullName>
    <description>Parent slot concerned by this customer slot</description>
    <label>Slot</label>
    <referenceTo>Slot__c</referenceTo>
    <relationshipLabel>Customer slots</relationshipLabel>
    <relationshipName>CustomerSlots</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/CustomerSlot__c/fields/StartDatetime__c.field-meta.xml
<CustomField>
    <fullName>StartDatetime__c</fullName>
    <description>Starting date and time of the customer slot</description>
    <formula>Slot__r.StartDatetime__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Starting date/time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/CustomerSlot__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <defaultValue>&quot;Booked&quot;</defaultValue>
    <description>Status of the customer slot</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Booked</fullName>
            </value>
            <value>
                <fullName>Checked-In</fullName>
            </value>
            <value>
                <fullName>No-Show</fullName>
            </value>
            <value>
                <fullName>Canceled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CustomerSlot__c/fields/TECH_StoreId__c.field-meta.xml
<CustomField>
    <fullName>TECH_StoreId__c</fullName>
    <description>to denormalize Account Store Id</description>
    <externalId>true</externalId>
    <label>TECH_StoreId</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CustomerSlot__c/fields/UUID__c.field-meta.xml
<CustomField>
    <fullName>UUID__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <label>UUID</label>
    <length>100</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/QueueBustingConfig__c/QueueBustingConfig__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Contains custom settings used to in the Queue busting application</description>
    <label>Queue busting App Config</label>
</CustomObject>

force-app/main/default/objects/QueueBustingConfig__c/fields/isCheckCustomerSlotDaysEnabled__c.field-meta.xml
<CustomField>
    <fullName>isCheckCustomerSlotDaysEnabled__c</fullName>
    <defaultValue>false</defaultValue>
    <description>define if we execute the timeframe check when a guest user try to create a customer slot</description>
    <label>isCheckCustomerSlotDaysEnabled</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/QueueBustingConfig__c/fields/isGeneratePdfEnabled__c.field-meta.xml
<CustomField>
    <fullName>isGeneratePdfEnabled__c</fullName>
    <defaultValue>false</defaultValue>
    <description>to enable/disable pdf generation</description>
    <label>isGeneratePdfEnabled</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/QueueBustingConfig__c/fields/NumberOfDaysAfterToCheck__c.field-meta.xml
<CustomField>
    <fullName>NumberOfDaysAfterToCheck__c</fullName>
    <description>Number of days after a relative slot to check if a client has booked a slot (filter : &lt; datetime)</description>
    <label>NumberOfDaysAfterToCheck</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/QueueBustingConfig__c/fields/NumberOfDaysBeforeToCheck__c.field-meta.xml
<CustomField>
    <fullName>NumberOfDaysBeforeToCheck__c</fullName>
    <description>Number of days before a relative slot to check if a client has booked a slot</description>
    <label>NumberOfDaysBeforeToCheck</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/QueueBustingConfig__c/fields/PdfEngine__c.field-meta.xml
<CustomField>
    <fullName>PdfEngine__c</fullName>
    <description>engine used to render pdf (default VF, accepted value VF/Heroku)</description>
    <inlineHelpText>engine used to render pdf (default VF, accepted value VF/Heroku)</inlineHelpText>
    <label>Pdf Engine</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/reCaptcha__c/reCaptcha__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>reCaptcha</label>
</CustomObject>

force-app/main/default/objects/reCaptcha__c/fields/isReCaptchaEnabled__c.field-meta.xml
<CustomField>
    <fullName>isReCaptchaEnabled__c</fullName>
    <defaultValue>true</defaultValue>
    <label>isReCaptchaEnabled</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/reCaptcha__c/fields/SecretKey__c.field-meta.xml
<CustomField>
    <fullName>SecretKey__c</fullName>
    <label>Secret Key</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Slot__c/Slot__c.object-meta.xml
<CustomObject>
    <description>Object containing final slots for stores.</description>
    <label>Créneau</label>
    <nameField>
        <displayFormat>S{00000}</displayFormat>
        <label>Slot number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Créneaux</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Slot__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <description>Store concerned by the slot</description>
    <label>Store</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Slots</relationshipLabel>
    <relationshipName>Slots</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Slot__c/fields/AvailablePositions__c.field-meta.xml
<CustomField>
    <fullName>AvailablePositions__c</fullName>
    <description>Number of available positions (number of customer that can enter) for this slot</description>
    <formula>RecurringSlot__r.AvailablePositions__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Available positions</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Slot__c/fields/BookedPositions__c.field-meta.xml
<CustomField>
    <fullName>BookedPositions__c</fullName>
    <description>Number of positions that are already booked by customer on this slot</description>
    <label>Booked positions</label>
    <summarizedField>CustomerSlot__c.ProvidedNumberOfPersons__c</summarizedField>
    <summaryFilterItems>
        <field>CustomerSlot__c.Status__c</field>
        <operation>notEqual</operation>
        <value>Canceled</value>
    </summaryFilterItems>
    <summaryForeignKey>CustomerSlot__c.Slot__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Slot__c/fields/RemainingPositions__c.field-meta.xml
<CustomField>
    <fullName>RemainingPositions__c</fullName>
    <description>Number of remaining positions (number of customer that can still book) for this slot</description>
    <formula>AvailablePositions__c - BookedPositions__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Remaining positions</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Slot__c/fields/StartDatetime__c.field-meta.xml
<CustomField>
    <fullName>StartDatetime__c</fullName>
    <description>Starting date and time of the slot</description>
    <label>Starting date/time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/User/fields/StoreId__c.field-meta.xml
<CustomField>
    <fullName>StoreId__c</fullName>
    <description>To store the store id of the user</description>
    <externalId>true</externalId>
    <label>StoreId</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/CustomerSlotBooking_Controller.cls
/**
* @author : Nicolas Greard(Salesforce)
* @date : 20/04/2020
* @description : class to handle the CustomerSlots
* @last modified date/comments :
*/
public without sharing class CustomerSlotBooking_Controller {
    //without sharing due to usage as guest user (better than open sharing)

    /**
    * @description searchTodayCustomerSlotByEmail
    * @param searchTerm : searchTerm (must be the email)
    * @return list of CustomerSlot__c
    */
    @AuraEnabled
    public static ResponseWrapper insertCS(String slotId,String lastName, String firstName, String email, String confirmEmail, Integer numPlaces,String token){
        System.debug(LoggingLevel.DEBUG,'slotId: ' + slotId + ' lastName: ' + lastName + ' firstName: '  + firstName + ' email: ' + email + ' numPlaces: ' + numPlaces);
        if(String.isNotBlank(slotId) && String.isNotBlank(email) && String.isNotBlank(confirmEmail)){
            if(!confirmEmail.equalsIgnoreCase(email)){
                throw new AuraHandledException(Label.CSCheckEmailsError);
            }

            String strStatus;
            try{
                reCaptcha__c captchaConfig = reCaptcha__c.getInstance();
                if(captchaConfig.isReCaptchaEnabled__c && !reCaptchaUtils.validateToken(captchaConfig.SecretKey__c,token)){
                    strStatus = Label.reCaptchaVerifFailed;
                }
            }
            catch(Exception ex){
                System.debug(LoggingLevel.ERROR, ex.getStackTraceString());
                System.debug(LoggingLevel.ERROR, ex.getMessage());
                System.debug(LoggingLevel.ERROR, ex.getTypeName());
                strStatus = Label.reCaptchaGenericError;
            }
            if (null!=strStatus){
                throw new AuraHandledException(strStatus);
            }

            //Get slot account
            List<Slot__c> sList = [SELECT Id,Account__c,StartDatetime__c,AvailablePositions__c,BookedPositions__c,RemainingPositions__c,
                                    Account__r.Name,Account__r.BillingStreet,Account__r.BillingPostalCode,Account__r.BillingCity,Account__r.StoreId__c
                                   FROM Slot__c 
                                   WHERE Id = :slotId];

            if(sList.isEmpty()){
                //do nothing as no slot found
                throw new AuraHandledException(Label.CSCreateUnknownSlotError);
            }
            else{
                Slot__c selectedSlot = sList[0];
                System.debug(LoggingLevel.DEBUG,'AccountId: ' + selectedSlot.Account__c);

                if(QueueBustingConfig__c.getInstance().isCheckCustomerSlotDaysEnabled__c){
                    //He/she can book up for a new slot (no more than 1 slot in a timeframe xx days)
                    Datetime startDate = selectedSlot.StartDatetime__c;
                    Datetime prevDays = Datetime.newInstance(startDate.year(), startDate.month(), startDate.day()).addDays(Integer.valueOf( QueueBustingConfig__c.getInstance().NumberOfDaysBeforeToCheck__c));
                    Datetime nextDays = Datetime.newInstance(startDate.year(), startDate.month(), startDate.day()).addDays(Integer.valueOf( QueueBustingConfig__c.getInstance().NumberOfDaysAfterToCheck__c));
                    List<CustomerSlot__c> currentCSSlots = [SELECT Id,Account__c,ProvidedEmail__c,Status__c,StartDatetime__c FROM CustomerSlot__c WHERE ProvidedEmail__c = :email AND Status__c IN ('Booked','Checked-In') AND StartDatetime__c >= :prevDays AND StartDatetime__c < :nextDays];
                    System.debug(LoggingLevel.DEBUG,'currentCSSlots: ' + currentCSSlots.size());
                    if(!currentCSSlots.isEmpty()){
                        throw new AuraHandledException(Label.CSCheckQuotaError);
                    }
                }

                //slot offset : increment by 10min
                //ex 40 position for 1 hour -> 17 position booked : resulting number = 20
                //Decimal timeOffsetMinutes = Math.ceil(60 * selectedSlot.BookedPositions__c / (selectedSlot.AvailablePositions__c * 10))*10;
                //System.debug(LoggingLevel.DEBUG,'timeOffsetMinutes: ' + timeOffsetMinutes);
                CustomerSlot__c toCreateCS = new CustomerSlot__c( 
                    Account__c = selectedSlot.Account__c,
                    TECH_StoreId__c = selectedSlot.Account__r.StoreId__c,
                    Slot__c = slotId,
                    ProvidedLastName__c = lastName,
                    ProvidedFirstName__c = firstName,
                    ProvidedEmail__c = email,
                    ProvidedNumberOfPersons__c = numPlaces,
                    Status__c = 'Booked',
                    ExpectedStartDatetime__c = selectedSlot.StartDatetime__c,
                    Position__c = selectedSlot.BookedPositions__c,
                    UUID__c = GuidUtil.NewGuid());

                String pdf = '';
                //render pdf with heroku
                if(QueueBustingConfig__c.getInstance().isGeneratePdfEnabled__c && 'Heroku'.equalsIgnoreCase(QueueBustingConfig__c.getInstance().PdfEngine__c) ){
                    System.debug(LoggingLevel.DEBUG,'PDF generated with Heroku');
                    pdf = Heroku_Utils.generatePDF(toCreateCS);
                }

                insert toCreateCS;

                //render with visualforce
                if(QueueBustingConfig__c.getInstance().isGeneratePdfEnabled__c && !'Heroku'.equalsIgnoreCase(QueueBustingConfig__c.getInstance().PdfEngine__c) ){
                    //data needed
                    System.debug(LoggingLevel.DEBUG,'PDF generated with Visualforce/Salesforce');
                    PDFDataWrapper pdfwrp = new PDFDataWrapper();
                    pdfwrp.uuid = toCreateCS.UUID__c;
                    pdfwrp.firstname = toCreateCS.ProvidedFirstName__c;
                    pdfwrp.lastname = toCreateCS.ProvidedLastName__c;
                    pdfwrp.startdatetime = selectedSlot.StartDatetime__c;
                    pdfwrp.numofpers = numPlaces;
                    pdfwrp.storename = selectedSlot.Account__r.Name;
                    pdfwrp.storestreet = selectedSlot.Account__r.BillingStreet;
                    pdfwrp.storepostalcode = selectedSlot.Account__r.BillingPostalCode;
                    pdfwrp.storecity = selectedSlot.Account__r.BillingCity;
                    String data = JSON.serialize(pdfwrp);
                    if(!Test.isRunningTest()){
                        Blob pdfAsBlob = new PageReference('/apex/CustomerSlotPdfGenerate?data=' + data).getContentAsPDF();
                        pdf = EncodingUtil.base64Encode(pdfAsBlob);
                    }
                }

                ResponseWrapper rw = new ResponseWrapper();
                rw.filename = QueueBustingConfig__c.getInstance().isGeneratePdfEnabled__c ? 'resa-creneaux-' + selectedSlot.StartDatetime__c.format('yyyy-MM-dd_HH-mm') + '.pdf' : '';
                rw.id = toCreateCS.UUID__c;
                System.debug(LoggingLevel.DEBUG,'pdf: ' + pdf.length());
                rw.pdf = pdf;
                return rw;
            }
        }
        else{
            throw new AuraHandledException(Label.CSCheckRequiredFieldsError);
        }
    }

    public class ResponseWrapper{
        @AuraEnabled
        public String filename;
        @AuraEnabled
        public String pdf;
        @AuraEnabled
        public String id;
    }
}