force-app/main/default/objects/Account/fields/StoreCustomerCount__c.field-meta.xml
<CustomField>
    <fullName>StoreCustomerCount__c</fullName>
    <defaultValue>0</defaultValue>
    <description>To store realtime customer count in the store</description>
    <label>Store Customer Count</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Account/fields/StoreId__c.field-meta.xml
<CustomField>
    <fullName>StoreId__c</fullName>
    <externalId>true</externalId>
    <label>Code Magasin</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Account/fields/StoreMaxCustomer__c.field-meta.xml
<CustomField>
    <fullName>StoreMaxCustomer__c</fullName>
    <defaultValue>10</defaultValue>
    <description>To store max customer that we can have in the store</description>
    <label>Store Max Customer</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Store.recordType-meta.xml
<RecordType>
    <fullName>Store</fullName>
    <active>true</active>
    <label>Magasin</label>
</RecordType>

force-app/main/default/objects/CustomerSlot__c/CustomerSlot__c.object-meta.xml
<CustomObject>
    <description>Object containing customer slots (booked, canceled or completed)</description>
    <label>Réservation client</label>
    <nameField>
        <displayFormat>BN{000000}</displayFormat>
        <label>Booking number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Réservations client</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/CustomerSlot__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Store concerned by the customer slot</description>
    <label>Store</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Customer slots</relationshipLabel>
    <relationshipName>CustomerSlots</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CustomerSlot__c/fields/ActualNumberOfPersons__c.field-meta.xml
<CustomField>
    <fullName>ActualNumberOfPersons__c</fullName>
    <description>Real number of total physical persons entering to the store (set by the store security)</description>
    <label>Actual number of persons</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/CustomerSlot__c/fields/ProvidedEmail__c.field-meta.xml
<CustomField>
    <fullName>ProvidedEmail__c</fullName>
    <description>Email provided by customer (set in customer slot form)</description>
    <label>Provided Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/CustomerSlot__c/fields/ProvidedName__c.field-meta.xml
<CustomField>
    <fullName>ProvidedName__c</fullName>
    <formula>ProvidedFirstName__c &amp; &quot; &quot; &amp; ProvidedLastName__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Provided Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CustomerSlot__c/fields/ProvidedNumberOfPersons__c.field-meta.xml
<CustomField>
    <fullName>ProvidedNumberOfPersons__c</fullName>
    <description>Provided number of total physical persons coming to the store (set in customer slot form)</description>
    <label>Provided number of persons</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/CustomerSlot__c/fields/StartDatetime__c.field-meta.xml
<CustomField>
    <fullName>StartDatetime__c</fullName>
    <description>Starting date and time of the customer slot</description>
    <formula>Slot__r.StartDatetime__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Starting date/time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/CustomerSlot__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <defaultValue>&quot;Booked&quot;</defaultValue>
    <description>Status of the customer slot</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Booked</fullName>
            </value>
            <value>
                <fullName>Checked-In</fullName>
            </value>
            <value>
                <fullName>No-Show</fullName>
            </value>
            <value>
                <fullName>Canceled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CustomerSlot__c/fields/StatusIcon__c.field-meta.xml
<CustomField>
    <fullName>StatusIcon__c</fullName>
    <formula>CASE(  Status__c,
&quot;Booked&quot;,
   IF( IsToday__c ,
        &quot;/fatcow/farmfresh/32/accept.png&quot;,
        &quot;/fatcow/farmfresh/32/error.png&quot; ),
&quot;/fatcow/farmfresh/32/delete.png&quot;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Status Icon</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CustomerSlot__c/fields/TechnicalStartDatetime__c.field-meta.xml
<CustomField>
    <fullName>TechnicalStartDatetime__c</fullName>
    <description>copy from slot to filter in SOSL mode</description>
    <label>Technical Start DateTime</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/CustomerSlot__c/fields/UUID__c.field-meta.xml
<CustomField>
    <fullName>UUID__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <label>UUID</label>
    <length>100</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/User/fields/StoreId__c.field-meta.xml
<CustomField>
    <fullName>StoreId__c</fullName>
    <description>To store the store id of the user</description>
    <externalId>true</externalId>
    <label>StoreId</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/CustomerSlot_Controller.cls
/**
* @author : Nicolas (Salesforce)
* @date : 20/04/2020
* @description : class to handle the CustomerSlots
* @last modified date/comments :
*/
public with sharing class CustomerSlot_Controller {
    
    /**
    * @description searchTodayCustomerSlotByEmail
    * @param searchTerm : searchTerm (must be the email)
    * @return list of CustomerSlot__c
    */
    @AuraEnabled
    public static List<CustomerSlot__c> searchTodayCustomerSlotByEmail(String searchTerm){
        System.debug(LoggingLevel.DEBUG,'searchTerm:' + searchTerm);

        User u = [SELECT Id,StoreId__c FROM User WHERE Id = :UserInfo.getUserId()];

        Date d = System.today();
        Date tomorrow = System.today() + 1;
        List<List<sObject>> searchList = [FIND :searchTerm IN ALL FIELDS RETURNING CustomerSlot__c(Id WHERE TechnicalStartDatetime__c >= :d AND TechnicalStartDatetime__c < :tomorrow LIMIT 4)];

        List<CustomerSlot__c> searchCustomerSlots = (CustomerSlot__c[])searchList[0];
        System.debug(LoggingLevel.DEBUG,'searchCustomerSlots:' + searchCustomerSlots.size());
        List<Id> csIds = new List<Id>();
        for(CustomerSlot__c cs : searchCustomerSlots){
            csIds.add(cs.Id);
        }
        System.debug(LoggingLevel.DEBUG,'csIds: ' + csIds.size());
        
        if(!csIds.isEmpty()){
            return Security.stripInaccessible(AccessType.READABLE,[SELECT Id,Name,Account__r.Name,ProvidedEmail__c,ProvidedName__c,StartDatetime__c,Status__c,ProvidedNumberOfPersons__c,StatusIcon__c FROM CustomerSlot__c WHERE Id IN :csIds]).getRecords();
        }
        return new List<CustomerSlot__c>();
    }

    /**
    * @description searchTodayCustomerSlotByEmail
    * @param searchTerm : searchTerm (must be the email)
    * @return list of CustomerSlot__c
    */
    @AuraEnabled(cacheable=true)
    public static CustomerSlot__c getSlotByIdOrUUID(String recordId){
        System.debug(LoggingLevel.DEBUG,'recordId:' + recordId);
        List<CustomerSlot__c> cs = Security.stripInaccessible(AccessType.READABLE,[SELECT Id,UUID__c,Status__c,StatusIcon__c FROM CustomerSlot__c WHERE Id = :recordId OR UUID__c = :recordId LIMIT 1]).getRecords();
        if(cs.isEmpty()){
            return new CustomerSlot__c();
        }
        else{
            return cs.get(0);
        }
    }

    @AuraEnabled
    public static Account getStoreCount(){
        User u = [SELECT Id,StoreId__c FROM User WHERE Id = :UserInfo.getUserId()];
        return [SELECT Id,Name,StoreId__c,StoreCustomerCount__c,StoreMaxCustomer__c FROM Account WHERE StoreId__c = :u.StoreId__c LIMIT 1];
    }

    @AuraEnabled
    public static Account setStoreCount(String op){
        System.debug(LoggingLevel.DEBUG,'op: ' + op);
        User u = [SELECT Id,StoreId__c FROM User WHERE Id = :UserInfo.getUserId()];
        Account store = [SELECT Id,Name,StoreId__c,StoreCustomerCount__c,StoreMaxCustomer__c FROM Account WHERE StoreId__c = :u.StoreId__c LIMIT 1];
        if(op.equalsIgnoreCase('minus')){
            store.StoreCustomerCount__c = Math.max(store.StoreCustomerCount__c - 1,0);
        }
        else{
            store.StoreCustomerCount__c = store.StoreCustomerCount__c + 1;
        }
        update store;
        return store;
    }

    @AuraEnabled
    public static void checkinCustomer(String id,Integer numOfpeople){
        System.debug(LoggingLevel.DEBUG,'id: ' + id + ' numOfpeople: ' + numOfpeople);
        CustomerSlot__c cs = [SELECT Id,Account__c,Status__c,ActualNumberOfPersons__c FROM CustomerSlot__c WHERE Id = :id];
        if(!cs.Status__c.equals('Booked')){
            throw new AuraException('Ce créneau ne peut pas/plus être utilisé');
        }
        cs.Status__c = 'Checked-In';
        cs.ActualNumberOfPersons__c = numOfpeople;
        update cs;

        Account store = [SELECT Id,Name,StoreId__c,StoreCustomerCount__c,StoreMaxCustomer__c FROM Account WHERE Id = :cs.Account__c LIMIT 1];
        store.StoreCustomerCount__c = store.StoreCustomerCount__c + numOfpeople;
        update store;
    }
}