force-app/main/default/objects/QueueBustingConfig__c/QueueBustingConfig__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Contains custom settings used to in the Queue busting application</description>
    <label>Queue busting App Config</label>
</CustomObject>

force-app/main/default/objects/QueueBustingConfig__c/fields/NumWeeksGeneratedSlots__c.field-meta.xml
<CustomField>
    <fullName>NumWeeksGeneratedSlots__c</fullName>
    <defaultValue>4</defaultValue>
    <description>Contains the number of weeks that is generated from recurring slots</description>
    <inlineHelpText>Contains the number of weeks that is generated from recurring slots</inlineHelpText>
    <label>Nb Weeks for recurring slot</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/RecurringSlot__c/RecurringSlot__c.object-meta.xml
<CustomObject>
    <description>Object containing recurring slots definition. Represent typical daily slot configuration.</description>
    <label>Créneau récurrent</label>
    <nameField>
        <displayFormat>RS{00000}</displayFormat>
        <label>Recurring slot number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Créneaux récurrents</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/RecurringSlot__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <description>Store concerned by the recurring slot</description>
    <label>Store</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Recurring slots</relationshipLabel>
    <relationshipName>RecurringSlots</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/RecurringSlot__c/fields/Duration__c.field-meta.xml
<CustomField>
    <fullName>Duration__c</fullName>
    <defaultValue>$Setup.QueueBustingConfig__c.DefaultSlotDuration__c</defaultValue>
    <description>Duration of the slots created by this recurrence in minutes</description>
    <label>Duration (in minutes)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/RecurringSlot__c/fields/EndTime__c.field-meta.xml
<CustomField>
    <fullName>EndTime__c</fullName>
    <description>Define the ending time of the slot</description>
    <inlineHelpText>Define the ending time of the slot</inlineHelpText>
    <label>End Time</label>
    <required>true</required>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/RecurringSlot__c/fields/IsActive__c.field-meta.xml
<CustomField>
    <fullName>IsActive__c</fullName>
    <defaultValue>true</defaultValue>
    <description>True when the recurring slot is active</description>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/RecurringSlot__c/fields/RecurrenceDays__c.field-meta.xml
<CustomField>
    <fullName>RecurrenceDays__c</fullName>
    <description>Contains list of week days for which this recurrence is applicable</description>
    <label>Recurrence days</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Monday</fullName>
            </value>
            <value>
                <fullName>Tuesday</fullName>
            </value>
            <value>
                <fullName>Wednesday</fullName>
            </value>
            <value>
                <fullName>Thursday</fullName>
            </value>
            <value>
                <fullName>Friday</fullName>
            </value>
            <value>
                <fullName>Saturday</fullName>
            </value>
            <value>
                <fullName>Sunday</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/RecurringSlot__c/fields/StartDatetime__c.field-meta.xml
<CustomField>
    <fullName>StartDatetime__c</fullName>
    <description>Date and time from which the recurrence will start</description>
    <label>Starting date/time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/RecurringSlot__c/fields/StartTime__c.field-meta.xml
<CustomField>
    <fullName>StartTime__c</fullName>
    <description>Define the starting time of the slot</description>
    <inlineHelpText>Define the starting time of the slot</inlineHelpText>
    <label>Start Time</label>
    <required>true</required>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/Slot__c/Slot__c.object-meta.xml
<CustomObject>
    <description>Object containing final slots for stores.</description>
    <label>Créneau</label>
    <nameField>
        <displayFormat>S{00000}</displayFormat>
        <label>Slot number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Créneaux</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Slot__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <description>Store concerned by the slot</description>
    <label>Store</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Slots</relationshipLabel>
    <relationshipName>Slots</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Slot__c/fields/Duration__c.field-meta.xml
<CustomField>
    <fullName>Duration__c</fullName>
    <description>Duration of the slot in minutes</description>
    <formula>RecurringSlot__r.Duration__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Duration (in minutes)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Slot__c/fields/IsActive__c.field-meta.xml
<CustomField>
    <fullName>IsActive__c</fullName>
    <defaultValue>true</defaultValue>
    <description>True when the slot is active</description>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Slot__c/fields/RecurringSlot__c.field-meta.xml
<CustomField>
    <fullName>RecurringSlot__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Recurring slot concerned by the slot</description>
    <label>Recurring slot</label>
    <referenceTo>RecurringSlot__c</referenceTo>
    <relationshipLabel>Slots</relationshipLabel>
    <relationshipName>Slots</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Slot__c/fields/StartDatetime__c.field-meta.xml
<CustomField>
    <fullName>StartDatetime__c</fullName>
    <description>Starting date and time of the slot</description>
    <label>Starting date/time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/classes/GenerateSlots_Service.cls
/**
* @author : Nicolas Greard(Salesforce)
* @date : 08/05/2020
* @description : class to handle slots generation
* @last modified date/comments :
*/
public with sharing class GenerateSlots_Service {
    
    private static Map<String, Integer> daysMap = new Map<String, Integer>{'Monday' => 0, 'Tuesday' => 1, 'Wednesday' => 2,'Thursday' => 3,'Friday' => 4,'Saturday' => 5,'Sunday' => 6};

    @InvocableMethod
    public static List<Integer> generateSlotsFromRecurringSlots(List<String> rsIds) {
        System.debug(LoggingLevel.DEBUG,'rsIds:' + rsIds);
        Integer totalInsert = 0;
        Integer numOfWeeks = Integer.valueOf(QueueBustingConfig__c.getInstance().NumWeeksGeneratedSlots__c);
        if(!rsIds.isEmpty()){
            for(Integer i=0; i < numOfWeeks; i++){
                totalInsert += generateSlotsFromRecurringSlotsIds(rsIds,i);
            }  
        }
        return new List<Integer> {totalInsert};
    }

    public static Integer generateSlotsFromRecurringSlotsIds(List<String> rsIds,Integer weekOffset){
        Integer totalInsert = 0;
        System.debug(LoggingLevel.DEBUG,'rsIds: ' + rsIds + ' weekOffset: ' + weekOffset);
        List<RecurringSlot__c> rslots= [SELECT Id,StartTime__c,RecurrenceDays__c,EndTime__c,Duration__c,Account__c
                                         FROM RecurringSlot__c
                                        WHERE Id IN :rsIds AND IsActive__c = true]; //only active recurring slots
        
        Map<String,Slot__c> slots = new Map<String,Slot__c>();
        Datetime now = Datetime.now();
        Set<String> accIds = new Set<String>();
        for(RecurringSlot__c rs : rslots){
            accIds.add(rs.Account__c);
            String[] days = rs.RecurrenceDays__c.split(';');
            Integer duration = Integer.valueOf(rs.Duration__c);
            //For all specified recurring days
            for(String d : days){
                //generate the date from day + week offset
                Date startOfWeek = Date.today().toStartofWeek().addDays(weekOffset*7);
                Date startDay = startOfWeek.addDays(daysMap.get(d));

                Time startTime = rs.StartTime__c;
                //generate slots for specific day between starttime and endtime from a recurring slot
                while(startTime < rs.EndTime__c){
                    Datetime slotSartdt = DateTime.newInstance(startDay, startTime);
                    //generate slot only if they are planned in the future
                    if(now < slotSartdt){
                        System.debug(LoggingLevel.FINEST,'create slot : ' + slotSartdt);
                        Slot__c s = new Slot__c(
                            Account__c = rs.Account__c,
                            StartDatetime__c = slotSartdt,
                            IsActive__c = true,
                            RecurringSlot__c = rs.Id
                        );
                        slots.put(s.Account__c + slotSartdt.format('yyyy-MM-dd\'T\'HH:mm'),s); //generate unique key to dedup
                    }
                    startTime = startTime.addMinutes(duration);
                }
            }
        }

        System.debug(LoggingLevel.DEBUG,'accIds: ' + accIds.size());
        List<Slot__c> existingSlots = [SELECT Id,Account__c,StartDatetime__c FROM Slot__c WHERE Account__c IN :accIds AND IsActive__c = true];
        Set<String> slotKeys = new Set<String>();
        for(Slot__c s : existingSlots){
            slotKeys.add(s.Account__c + s.StartDatetime__c.format('yyyy-MM-dd\'T\'HH:mm'));
        }

        System.debug(LoggingLevel.DEBUG,'slots generated: ' + slots.size());
        if(!slots.isEmpty()){
            //remove duplicate
            List<Slot__c> toInsert = new List<Slot__c>();
            for(String key : slots.keySet()){
                if(!slotKeys.contains(key)){
                    toInsert.add(slots.get(key));
                }
            }

            totalInsert = toInsert.size();
            System.debug(LoggingLevel.DEBUG,'toInsert: ' + totalInsert);
            if(!toInsert.isEmpty()){
                insert toInsert;
            }
        }
        return totalInsert;
    }

}